Added "dump-db" command

diff --git a/manage-stack b/manage-stack
--- a/manage-stack
+++ b/manage-stack
@@ -382,6 +382,7 @@ function usage() {
 	echo "       manage-stack [-s <stackName>] {benchmark|nobenchmark}"
 	echo "       manage-stack [-s <stackName>] {attach|shell|logs} <nodeId>"
 	echo "       manage-stack [-s <stackName>] {config|edit-config}"
+	echo "       manage-stack [-s <stackName>] dump-db <nodeId> <outputFile>"
 }
 
 function benchmark() {
@@ -421,6 +422,59 @@ function editConfig() {
 	rm -f "${tmpfile}"
 
 	return 0
+}
+
+function dumpDB() {
+	local nodeID outputFile
+	local tmpfile retval
+
+	nodeID="$1"
+	outputFile="$2"
+
+	if [ -z "${nodeID}" -o -z "${outputFile}" ]; then
+		echo "Usage: manage-stack [-s <stackName>] dump-db <nodeId> <outputFile>" >&2
+
+		return 1
+	fi
+
+	shell "${nodeID}" sh -c "$(cat <<\_EOF_
+		set -e
+		while true; do
+			cd /
+			rm -rf /db2
+			mkdir /db2
+			cd /db2
+			before="$(cd /db && sha1sum * | sha1sum | awk '{ print $1 }')"
+			cp /db/* .
+			after="$(cd /db && sha1sum * | sha1sum | awk '{ print $1 }')"
+			verify="$(cd /db2 && sha1sum * | sha1sum | awk '{ print $1 }')"
+			if [ "${before}" = "${after}" ]; then
+				if [ "${verify}" != "${before}" ]; then
+					echo "ERROR" >&2
+					exit 1
+				fi
+				break
+			fi
+			sleep 0.1
+		done
+		cd /db2
+		rm -f /db.tar
+		tar -cf /db.tar *
+_EOF_
+)" || return 1
+
+	tmpfile="$(mktemp)"
+
+	shell "${nodeID}" gzip -9c /db.tar > "${tmpfile}"
+	retval="$?"
+
+	if [ "${retval}" = '0' ]; then
+		cp "${tmpfile}" "${outputFile}"
+	fi
+
+	rm -f "${tmpfile}"
+
+	return "${retval}"
 }
 
 cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1
@@ -515,6 +569,10 @@ case "${action}" in
 		;;
 	edit-config)
 		editConfig "$@"
+		exit "$?"
+		;;
+	dump-db)
+		dumpDB "$@"
 		exit "$?"
 		;;
 	help)
